-- Femantic Database Schema
-- Production-ready schema for multi-user real-time analytics
-- Version 1.2 – Super User + Invite Token + Restricted Clients

-- Users
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role VARCHAR(20) DEFAULT 'pro' CHECK (role IN ('admin', 'pro', 'client')),
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted')),
    membership VARCHAR(20) DEFAULT 'free' CHECK (membership IN ('free', 'premium', 'expired')),
    is_active BOOLEAN DEFAULT TRUE,
    parent_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    brand_name VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_parent ON users(parent_id);

-- Websites
CREATE TABLE IF NOT EXISTS websites (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    api_key VARCHAR(64) UNIQUE NOT NULL,
    public_key VARCHAR(32) UNIQUE,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_websites_owner ON websites(owner_id);
CREATE INDEX IF NOT EXISTS idx_websites_api_key ON websites(api_key);

-- Invite Tokens (generated by Super/Pro users for their clients)
CREATE TABLE IF NOT EXISTS invite_tokens (
    id SERIAL PRIMARY KEY,
    token VARCHAR(64) UNIQUE NOT NULL,
    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    allowed_website_ids JSONB DEFAULT '[]',
    allowed_metrics JSONB DEFAULT '["visitors", "pageviews", "utm"]',
    label VARCHAR(255),
    max_uses INTEGER DEFAULT 1,
    used_count INTEGER DEFAULT 0,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invite_tokens_token ON invite_tokens(token);
CREATE INDEX IF NOT EXISTS idx_invite_tokens_created_by ON invite_tokens(created_by);

-- Client → Website access mapping
CREATE TABLE IF NOT EXISTS client_website_access (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    website_id INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    allowed_metrics JSONB DEFAULT '["visitors", "pageviews", "utm"]',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, website_id)
);

CREATE INDEX IF NOT EXISTS idx_client_access_user ON client_website_access(user_id);
CREATE INDEX IF NOT EXISTS idx_client_access_website ON client_website_access(website_id);

-- Sessions
CREATE TABLE IF NOT EXISTS sessions (
    id SERIAL PRIMARY KEY,
    website_id INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    visitor_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) UNIQUE NOT NULL,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    duration INTEGER DEFAULT 0,
    pageview_count INTEGER DEFAULT 0,
    is_bounce BOOLEAN DEFAULT TRUE,
    country VARCHAR(100),
    device VARCHAR(50),
    browser VARCHAR(100),
    os VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_sessions_website ON sessions(website_id);
CREATE INDEX IF NOT EXISTS idx_sessions_visitor ON sessions(visitor_id);
CREATE INDEX IF NOT EXISTS idx_sessions_session_id ON sessions(session_id);

-- Pageviews
CREATE TABLE IF NOT EXISTS pageviews (
    id SERIAL PRIMARY KEY,
    website_id INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    session_id INTEGER REFERENCES sessions(id),
    visitor_id VARCHAR(64),
    path VARCHAR(512) NOT NULL,
    title VARCHAR(512),
    referrer VARCHAR(512),
    user_agent TEXT,
    ip_address VARCHAR(45),
    country VARCHAR(100),
    city VARCHAR(100),
    device VARCHAR(50),
    browser VARCHAR(100),
    os VARCHAR(100),
    screen_width INTEGER,
    screen_height INTEGER,
    language VARCHAR(20),
    utm_source VARCHAR(100),
    utm_medium VARCHAR(100),
    utm_campaign VARCHAR(100),
    is_bot BOOLEAN DEFAULT FALSE,
    traffic_score FLOAT DEFAULT 1.0,
    traffic_label VARCHAR(20) DEFAULT 'human',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pageviews_website_created ON pageviews(website_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_session ON pageviews(session_id);
CREATE INDEX IF NOT EXISTS idx_pageviews_visitor ON pageviews(visitor_id);

-- Events
CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    website_id INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    session_id VARCHAR(64),
    visitor_id VARCHAR(64),
    event_name VARCHAR(100) NOT NULL,
    event_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_website ON events(website_id);
CREATE INDEX IF NOT EXISTS idx_events_name ON events(event_name);

-- Memberships
CREATE TABLE IF NOT EXISTS memberships (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan VARCHAR(50) DEFAULT 'free',
    status VARCHAR(20) DEFAULT 'free',
    started_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    stripe_subscription_id VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id);
