import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, View } from "react-native";
import { getLiveStats, getWebsites, LiveStats, Website } from "../api";
import { useAuth } from "../AuthContext";
import { colors, ui } from "../theme";
export function AnalyticsScreen() { const { token } = useAuth(); const [sites, setSites] = useState<Website[]>([]); const [selected, setSelected] = useState<Website | null>(null); const [live, setLive] = useState<LiveStats | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!token) return; getWebsites(token).then((rows) => { setSites(rows); setSelected(rows[0] || null); }).catch(() => undefined); }, [token]);
  useEffect(() => { if (!token || !selected) { setLoading(false); return; } let mounted = true; const load = async () => { try { const data = await getLiveStats(token, selected.id); if (mounted) setLive(data); } finally { if (mounted) setLoading(false); } }; load(); const timer = setInterval(load, 15000); return () => { mounted = false; clearInterval(timer); }; }, [token, selected]);
  return <ScrollView style={ui.screen} contentContainerStyle={ui.scroll}><Text style={ui.eyebrow}>REALTIME / AUTO REFRESH 15S</Text><Text style={ui.title}>Live pulse.</Text><Text style={ui.subtitle}>See what human visitors are doing right now.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginTop: 20 }} contentContainerStyle={{ gap: 8 }}>{sites.map((site) => <Pressable key={site.id} onPress={() => setSelected(site)} style={[ui.outlineButton, { paddingHorizontal: 15, borderColor: selected?.id === site.id ? colors.accent : colors.line }]}><Text style={{ color: selected?.id === site.id ? colors.accent : colors.text, fontWeight: "800" }}>{site.name}</Text></Pressable>)}</ScrollView>{loading ? <ActivityIndicator color={colors.accent} style={{ marginTop: 40 }} /> : !selected ? <View style={[ui.panel, { marginTop: 25 }]}><Text style={{ color: colors.text, fontWeight: "800" }}>Connect a website to see live analytics.</Text></View> : <><View style={{ flexDirection: "row", gap: 10, marginTop: 25 }}><View style={[ui.panel, { flex: 1 }]}><Text style={ui.label}>LIVE VISITORS</Text><Text style={{ color: colors.green, fontSize: 34, fontWeight: "900" }}>{live?.live_visitors ?? 0}</Text></View><View style={[ui.panel, { flex: 1 }]}><Text style={ui.label}>LAST 5 MIN</Text><Text style={{ color: colors.accent, fontSize: 34, fontWeight: "900" }}>{live?.pageviews_last_5min ?? 0}</Text></View></View><View style={[ui.panel, { marginTop: 10 }]}><Text style={{ color: colors.text, fontSize: 17, fontWeight: "900" }}>Top live pages</Text>{(live?.top_pages_live || []).map((page) => <View key={page.path} style={{ borderTopColor: colors.line, borderTopWidth: 1, paddingVertical: 13, marginTop: 10, flexDirection: "row", justifyContent: "space-between" }}><Text style={{ color: colors.text, flex: 1 }} numberOfLines={1}>{page.path}</Text><Text style={{ color: colors.accent, fontWeight: "900" }}>{page.views}</Text></View>)}{!live?.top_pages_live?.length && <Text style={ui.subtitle}>No human pageviews in the current window.</Text>}</View></>}</ScrollView>; }
