import React, { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { createWebsite, getWebsites, Website } from "../api";
import { useAuth } from "../AuthContext";
import { colors, ui } from "../theme";
export function SitesScreen() { const { token, user } = useAuth(); const [sites, setSites] = useState<Website[]>([]); const [name, setName] = useState(""); const [domain, setDomain] = useState(""); const [busy, setBusy] = useState(false); const canCreate = user?.role === "admin" || user?.role === "pro";
  async function load() { if (token) setSites(await getWebsites(token)); } useEffect(() => { load().catch(() => undefined); }, [token]);
  async function add() { if (!token || !name.trim() || !domain.trim()) return Alert.alert("Missing details", "Enter a site name and domain."); try { setBusy(true); await createWebsite(token, name, domain); setName(""); setDomain(""); await load(); } catch (error: any) { Alert.alert("Could not connect site", error?.response?.data?.detail || "Try again."); } finally { setBusy(false); } }
  return <ScrollView style={ui.screen} contentContainerStyle={ui.scroll}><Text style={ui.eyebrow}>CONNECTED SITES</Text><Text style={ui.title}>Your properties.</Text><Text style={ui.subtitle}>Choose a site to power your traffic reports.</Text><View style={{ marginTop: 24, gap: 10 }}>{sites.map((site) => <View key={site.id} style={ui.panel}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Text style={{ color: colors.text, fontSize: 17, fontWeight: "900" }}>{site.name}</Text><Text style={{ color: site.is_active ? colors.green : colors.red, fontWeight: "800" }}>{site.is_active ? "ACTIVE" : "OFFLINE"}</Text></View><Text style={ui.subtitle}>{site.domain}</Text></View>)}</View>{canCreate && <View style={[ui.panel, { marginTop: 20 }]}><Text style={{ color: colors.text, fontSize: 17, fontWeight: "900", marginBottom: 15 }}>Connect another site</Text><Text style={ui.label}>SITE NAME</Text><TextInput placeholder="My publication" placeholderTextColor={colors.muted} style={ui.input} value={name} onChangeText={setName} /><Text style={[ui.label, { marginTop: 14 }]}>DOMAIN</Text><TextInput autoCapitalize="none" placeholder="example.com" placeholderTextColor={colors.muted} style={ui.input} value={domain} onChangeText={setDomain} /><Pressable onPress={add} disabled={busy} style={[ui.button, { marginTop: 16, opacity: busy ? 0.6 : 1 }]}><Text style={ui.buttonText}>{busy ? "CONNECTING..." : "CONNECT SITE"}</Text></Pressable></View>}{!canCreate && <View style={[ui.panel, { marginTop: 20 }]}><Text style={{ color: colors.orange, fontWeight: "800" }}>Website access is managed by your account owner.</Text></View>}</ScrollView>; }
